# docker-compose.yml

version: '3'

services:
  project:
    build: 
      context: ./project
      dockerfile: Dockerfile
    volumes:
      - ../project/
      - .:/code
    command: uvicorn server:app --reload --workers 1 --host 0.0.0.0 --port 8080
    env_file:
      - ./.env
    depends_on:
      - db
    restart: "on-failure"
    
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: "on-failure"
  
volumes:
  postgres_data: